In [105]:
'''
작성일자 : 2021-04-26
작성자 : 이예희
작성내용 : 파이썬 예제 - 원하는 식사의 타입(한식, 양식, 중식 등)에 따라 타입에 맞는 음식 랜덤 출력

식사 입력하는 경우 랜덤으로 메뉴 나오는 것
1. 당신은 어떤 식사를 드시겠습니까? (한식, 중식, 일식, 분식)
2. 당신은 후식을 드시겠습니까? (Y/N)
ex) 서초 맛집 시트 활용하여 메뉴 넣기
korean = []
chinese = []
japanese = []
flour = []
3. if 구문활용하고  
for 구문, 리스트 컴프리헨션 활용하여 메뉴 랜덤으로 print하기
menu = []
dessert = []
'''

'\n작성일자 : 2021-04-26\n작성자 : 이예희\n작성내용 : 파이썬 예제 - 원하는 식사의 타입(한식, 양식, 중식 등)에 따라 타입에 맞는 음식 랜덤 출력\n\n식사 입력하는 경우 랜덤으로 메뉴 나오는 것\n1. 당신은 어떤 식사를 드시겠습니까? (한식, 중식, 일식, 분식)\n2. 당신은 후식을 드시겠습니까? (Y/N)\nex) 서초 맛집 시트 활용하여 메뉴 넣기\nkorean = []\nchinese = []\njapanese = []\nflour = []\n3. if 구문활용하고  \nfor 구문, 리스트 컴프리헨션 활용하여 메뉴 랜덤으로 print하기\nmenu = []\ndessert = []\n'

In [106]:
import pandas as pd

food_list = pd.read_csv("E:\\Study\\0_YGL\\python\\data\\학동역음식점목록.csv", header = 1)
print(food_list)

# print(type(food_list))

    순번 종류(한식, 중식, 일식, 분식, 후식 등)     음식점명  별점 (1~5점, 5점 : 아주맛있음)  지도 (링크)
0    1                       후식      이디야                    4.0      NaN
1    2                       분식     맥도날드                    3.0      NaN
2    3                       분식     서브웨이                    4.0      NaN
3    4                       한식   명동 칼국수                    5.0      NaN
4    5                       일식     토가라시                    4.0      NaN
5    6                       한식     나주곰탕                    4.0      NaN
6    7                       분식      KFC                    3.0      NaN
7    8                       한식     화포식당                    1.0      NaN
8    9                       한식    밥짓는카페                    5.0      NaN
9   10                       한식  부산아지매국밥                    4.0      NaN
10  11                       한식      류몽민                    3.0      NaN
11  12                       중식       홍명                    4.0      NaN
12  13                       한식     돼지국밥                    2.0      NaN
13  14                       한식       전집                    4.0      NaN
14  15                       일식   부엉이 식당                    3.0      NaN
15  16                       분식      김가네                    3.0      NaN
16  17                       후식    바나프레소                    4.0      NaN
17  18                       후식     스타벅스                    4.0      NaN
18  19                       분식   노브랜드버거                    5.0      NaN
19  20                       중식       송림                    4.0      NaN
20  21                       한식     깐부치킨                    4.0      NaN
21  22                       중식     교동짬뽕                    4.0      NaN
22  23                       한식       본죽                    4.0      NaN
23  24                       한식   진미평양냉면                    5.0      NaN
24  25                      NaN      NaN                    NaN      NaN

In [107]:
print(food_list.shape)
print(len(food_list.index))
print(food_list.columns)
# column name 변경
food_list.rename(columns = {"종류(한식, 중식, 일식, 분식, 후식 등)":"종류",\
                           "별점 (1~5점, 5점 : 아주맛있음)":"별점",\
                           "지도 (링크)":"지도"}, inplace = True)
# inplace = True 안해주면 내용 저장안됨.
# 아래것도 같은내용. 인덱스지정해서 변경도 가능.
# food_list.rename(columns = {1:"종류", 3:"별점", 5:"지도"})

(25, 5)
25
Index(['순번', '종류(한식, 중식, 일식, 분식, 후식 등)', '음식점명', '별점 (1~5점, 5점 : 아주맛있음)',
       '지도 (링크)'],
      dtype='object')

In [108]:
food_list

    순번   종류     음식점명   별점  지도
0    1   후식      이디야  4.0 NaN
1    2   분식     맥도날드  3.0 NaN
2    3   분식     서브웨이  4.0 NaN
3    4   한식   명동 칼국수  5.0 NaN
4    5   일식     토가라시  4.0 NaN
5    6   한식     나주곰탕  4.0 NaN
6    7   분식      KFC  3.0 NaN
7    8   한식     화포식당  1.0 NaN
8    9   한식    밥짓는카페  5.0 NaN
9   10   한식  부산아지매국밥  4.0 NaN
10  11   한식      류몽민  3.0 NaN
11  12   중식       홍명  4.0 NaN
12  13   한식     돼지국밥  2.0 NaN
13  14   한식       전집  4.0 NaN
14  15   일식   부엉이 식당  3.0 NaN
15  16   분식      김가네  3.0 NaN
16  17   후식    바나프레소  4.0 NaN
17  18   후식     스타벅스  4.0 NaN
18  19   분식   노브랜드버거  5.0 NaN
19  20   중식       송림  4.0 NaN
20  21   한식     깐부치킨  4.0 NaN
21  22   중식     교동짬뽕  4.0 NaN
22  23   한식       본죽  4.0 NaN
23  24   한식   진미평양냉면  5.0 NaN
24  25  NaN      NaN  NaN NaN

In [109]:
# drop_food = food_list.drop(food_list.index[0])
# drop_food

# food_list.index[4]
food_list.drop('순번', axis = 1, inplace = True)
food_list.drop('별점', axis = 1, inplace = True)
food_list.drop('지도', axis = 1, inplace = True)

In [110]:
food_list

     종류     음식점명
0    후식      이디야
1    분식     맥도날드
2    분식     서브웨이
3    한식   명동 칼국수
4    일식     토가라시
5    한식     나주곰탕
6    분식      KFC
7    한식     화포식당
8    한식    밥짓는카페
9    한식  부산아지매국밥
10   한식      류몽민
11   중식       홍명
12   한식     돼지국밥
13   한식       전집
14   일식   부엉이 식당
15   분식      김가네
16   후식    바나프레소
17   후식     스타벅스
18   분식   노브랜드버거
19   중식       송림
20   한식     깐부치킨
21   중식     교동짬뽕
22   한식       본죽
23   한식   진미평양냉면
24  NaN      NaN

In [111]:
# 둘 다 같음
# 데이터.drop(제거할row인덱스)
# food_list.drop(food_list.index[24])
food_list = food_list.drop(24)

In [58]:
# food_list["종류"]
food_list["종류"]

food_list.loc[0]
food_list.iloc[0]

food_list.loc[0]["종류"]

'후식'

In [112]:
# food_list["종류"]

for li in food_list:
    food_factor = food_list.drop("음식점명", axis = 1)
    food_factor = food_factor.drop_duplicates()
    
# print(food_factor)

for n in food_factor:
    menu = list(food_factor[n])

print(menu)
print(menu[2])

['후식', '분식', '한식', '일식', '중식']
한식

In [317]:
# for m in menu:
# #     print(type(m))
#     if m == list(food_list["종류"]):
# #         m += list(food_list("음식점명"))

# for f in food_list["종류"]:
#     if f in "후식":
#         후식 = food_list["음식점명"]

        
for f in range(len(food_list["종류"])):
    if "후식" in food_list.loc[f]["종류"]:
        str(f)



# for f in range(len(food_list["종류"])):
#     for m in range(len(menu)):
#         if menu[m] in food_list.loc[f]["종류"]:
#             print(f)

index = []
후식 = []
count = 0

for m in range(len(menu)):
    for f in range(len(food_list["종류"])):
        if menu[m] in food_list.loc[f]["종류"]:
            index += [f]

    
for i in range(len(index)):
    if index[i] <= index[i+1]:
        idx = index[i]
        후식 += list(food_list.loc[idx]["음식점명"])
        count += 1
#         print(후식)
#         idx = index[i]
#         print(idx)
#         food_list[int[idx]]
        if count == 2:
            break

# for i in range(len(index)):
#     for a :
#         idx = index[i]
#         후식 = food_list.loc[idx]["음식점명"]
#         if index[i] <= index[i+1]:
#             break

print(후식)

        
#         print(idx)

#     print(index[i])
#     print(index[i+1])
#     if i == 0:
#         break


# index[0]
# food_list[index[1]]["음식점명"]
# print(food_list.index)

# for m in food_list["종류"]:
#     if m in "후식":
#         print(food_list.index["종류" in 후식])
        
# 후식 in list(food_list["종류"])


# print(후식)

# print(m)
# food_list["종류"]

['dfdfdf', '이', '디', '야', '바', '나', '프', '레', '소']

In [ ]:
print("오늘의 메뉴를 정해드립니다")
print("드시길 희망히시는 음식의 종류를 적어주세요")
print("1 : 한식, 2 : 중식, 3 : 일식, 4 : 분식, 5 : 후식")
select = int(input())

# for rand in menu:
# 랑 다름. 이상태는 rand가 문자열을 출력함.
# 지금은 인덱스 출력.
for rand in range(len(menu)):
    if select == menu[rand]:
        print(rand)